name: tm_auto_caller
description: TM Auto Caller v4
version: 4.0.0+4

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_contacts: ^1.1.9+2
  url_launcher: ^6.2.0
  permission_handler: ^10.4.5
  sqflite: ^2.3.0
  path: ^1.8.3
  provider: ^6.0.5
  excel: ^3.0.0
  share_plus: ^7.2.2
  path_provider: ^2.1.1
  connectivity_plus: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
